name: Java CI with Gradle

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate RSA keys
        run: |
          mkdir -p src/main/resources
          openssl genpkey -algorithm RSA -out src/main/resources/private.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -pubout -in src/main/resources/private.pem -out src/main/resources/public.pem
          
      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        env:
          TESTCONTAINERS_RYUK_DISABLED: "true"
          DOCKER_HOST: tcp://localhost:2375
        run: ./gradlew test --no-daemon

      - name: Stop all Docker containers
        run: docker stop $(docker ps -aq) || true
