name: Java CI with Gradle

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Generate RSA keys
        run: |
          mkdir -p src/main/resources
          openssl genpkey -algorithm RSA -out src/main/resources/private.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -pubout -in src/main/resources/private.pem -out src/main/resources/public.pem

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
